site_name: S.T.A.R. Project
repo_url: https://github.com/xKabbe/star
theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Software:
    - General Tech Stack: general_tech_stack.md
    - Dashboard: dashboard.md
    - Backend: backend.md
    - Simulator: simulator.md
  - About:
    - About Us: about_us.md
    - License: license.md
    - Release Notes: release_notes.md
