name: Hello World Workflow
run-name: ${{ github.actor }} is running the Hello World Workflow 💻

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Hello World
        run: echo "Hello, World!"
